export const COMPANY = {
  name: 'GLOBAL NEXUS SOLUTIONS LLC',
  shortName: 'GNS',
  alternateNames: ['Global Solution Oman', 'Oman Solution', 'GNS Oman', 'Global Nexus Solutions'],
  email: 'omanigns@gmail.com',
  phone: '+96879924362',
  phoneDisplay: '+968 79924362',
  phoneSchema: '+968-79924362',
  crNumber: '1594268',
  country: 'Sultanate of Oman',
  countryCode: 'OM',
  foundingDate: '2024',
  currency: 'OMR',
  baseDescription: 'Global Solution Oman - Professional services company in the Sultanate of Oman. Proposition de services trading, IT consulting, logistics, import-export and administrative solutions.',
} as const;
